data_pack:
  name: datapack
  pack_format: 71
  description: Salvar el mundo
  load:
    - data: data
    - data/mc2/modules: src
    - pack.png: zpack.png

resource_pack:
  name: texturepack
  pack_format: 55
  description: "yo cuando poggers: poggers"
  load:
    - assets: resources
    - pack.png: zpack2.png

require:
  - bolt
  - bookshelf.module.view

pipeline:
  - mecha
  - setup
  - utils
  - damage
  - finish
  - gen.lang
  - gen.models
  - gen.creative
  - gen.components
  - beet.contrib.format_json

meta:

  bolt:
    entrypoint:
      - mc2:main

  format_json:
    indent: 4
    sort_keys: true

  lsp:
    excluded_plugins:
      - setup
      - utils
      - damage
      - finish
      - gen.lang
      - gen.models
      - gen.creative
      - gen.components
      - beet.contrib.format_json

output: bin