data_pack:
  name: datapack
  pack_format: 71
  description: Salvar el mundo
  load:
    - data: data
    - data/mc2/modules: src
    - pack.png: zpack.png

require:
  - bolt

pipeline:
  - mecha
  - beet.contrib.load
  - setup
  - utils
  - damage
  - jsons
  - finish

meta:
  bolt:
    entrypoint:
      - mc2:main
  load:
    data_pack: "bs.view"
  lsp:
    excluded_plugins:
      - setup
      - utils
      - damage
      - jsons
      - finish

output: bin